# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
  - package-ecosystem: "nuget"
    directory: "/csharp/PhoneNumbers"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      PhoneNumbers_minor_patch_updates:
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "nuget"
    directory: "/csharp/PhoneNumbers.Extensions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      PhoneNumbers_Extensions_minor_patch_updates:
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "nuget"
    directory: "/csharp/PhoneNumbers.Extensions.Test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      PhoneNumbers_Extensions_Test_minor_patch_updates:
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "nuget"
    directory: "/csharp/PhoneNumbers.Test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      PhoneNumbers_Test_minor_patch_updates:
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
