# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "create_new_release_on_new_metadata_update"

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  create_new_release_on_new_metadata_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Get new metadata information and create new GitHub release
        timeout-minutes: 30
        run: |
          bash lib/github-actions-metadata-update.sh ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
